### ISSUE TITLE
Cannot run on MNIST data

### ISSUE THREAD

**Issue by ghost** [piiswrong/dec#24]
Hello, 
I followed all the proper instructions to get the data (./get_data.sh), then (python make_mnist_data.py ) and now I get this error when running:

[ad@turing dec]$ python dec.py mnist
/usr/lib64/python2.7/site-packages/sklearn/lda.py:6: DeprecationWarning: lda.LDA has been moved to discriminant_analysis.LinearDiscriminantAnalysis in 0.17 and will be removed in 0.19
  "in 0.17 and will be removed in 0.19", DeprecationWarning)
Traceback (most recent call last):
  File "dec.py", line 768, in <module>
    DisKmeans(db, lam)
  File "dec.py", line 684, in DisKmeans
    ret, net = extract_feature('net.prototxt', 'exp/'+db+'/save_iter_100000.caffemodel', ['output'], N, True, 0)
  File "dec.py", line 576, in extract_feature
    caffe.Net.set_phase_train()
AttributeError: type object 'Net' has no attribute 'set_phase_train'

Could you help me understand what I need to do?

**Comment by pbruneau** [comment]
I'm also stuck at the same stage, and right abandoning investigating this repo, as there seems to be no support.

Apparently there is an mxnet maintained implementation here: https://github.com/apache/incubator-mxnet/tree/master/example/deep-embedded-clustering

**Comment by xinyeDu** [comment]
Hello,I also encountered the same problem. Have you solved this problem?
