### ISSUE TITLE
Import error , no modul named _caffe

### ISSUE THREAD

**Issue by 450586509** [piiswrong/dec#3]
recently, I read your paper. And I think in is very cool.
I do as follows:
1. I installed caffe on windows 10.
2. git clone your code. 
3. cd mnist; ./get_data.sh 
4. cd dec; python make_mnist_data.py

then I got the error information:
H:\project\windows_caffe\dec\dec\dec>python make_mnist_data.py
Traceback (most recent call last):
  File "make_mnist_data.py", line 1, in <module>
    import dec
  File "H:\project\windows_caffe\dec\dec\dec\dec.py", line 12, in <module>
    import caffe
  File "../caffe/python\caffe__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "../caffe/python\caffe\pycaffe.py", line 10, in <module>
    from ._caffe import Net, SGDSolver
ImportError: No module named _caffe

Could you please tell me what's wrong with it . Thank you very much.

**Comment by 450586509** [comment]
I think , I get the answer. "To run, please first build our custom version of Caffe included in this package following the official guide"
